name: Build Docs Image

on:
  release:
    types: [published]
  pull_request:

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      trunkver: ${{ steps.trunkver.outputs.trunkver }}
    steps:
      - name: Get a version tag
        id: trunkver
        uses: crftd-tech/trunkver@main
        with:
          prerelease: ${{ github.ref == 'refs/heads/master' && 'false' || 'true' }}
  build-and-push:
    needs: [generate-version]
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ghcr.io/elifesciences/api-raml-docs
      IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && needs.generate-version.outputs.trunkver || format('{0}-{1}', github.head_ref || github.ref_name, needs.generate-version.outputs.trunkver) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install
        run: npm install
      - name: compile the dist/
        run: node compile.js
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          load: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_REPO }}:${{ github.sha }}
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
